name: 夢沉抹大拉
description: 一个追寻抹大拉之地的geeker
meta_description: "生命不息，折腾不止"

baseurl: /
url: 'http://blog.imaou.com'
author: 木桩
logo: false

markdown: redcarpet
highlighter: pygments

paginate: 10

gems:
- jekyll-redirect-from
- jekyll-sitemap
